variable "ENGINE" {}
variable "ENGINE_VERSION" {}
variable "INSTANCE_CLASS" {}
variable "PG_FAMILY" {}
variable "PRIVATE_SUBNET_IDS" {}
variable "VPC_ID" {}
variable "PORT" {}
variable "ALLOW_SG_CIDR" {}
variable "PROJECT" {}
variable "ENV" {}
variable "NUMBER_OF_NODES" {}
